version: '3.7'

services:
    php_fpm:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www/
        container_name: php
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - tempest

    nginx_url:
        image: nginx:alpine
        container_name: nginx
        networks:
            - tempest
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php_fpm
        ports:
            - "8081:80"

networks:
    tempest:
        driver: bridge
